CREATE TABLE BATCH_JOB_INSTANCE
(
    JOB_INSTANCE_ID BIGINT       NOT NULL AUTO_INCREMENT,
    JOB_NAME        VARCHAR(100) NOT NULL,
    JOB_KEY         VARCHAR(32)  NOT NULL,
    JOB_PARAMS      VARCHAR(512) NOT NULL,
    CREATE_TIME     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (JOB_INSTANCE_ID),
    UNIQUE UNIQ_JOB_INST(JOB_NAME, JOB_KEY)
) ENGINE=InnoDB;

CREATE TABLE BATCH_JOB_EXECUTION
(
    JOB_EXECUTION_ID BIGINT       NOT NULL AUTO_INCREMENT,
    VERSION          BIGINT       NOT NULL DEFAULT 0,
    JOB_INSTANCE_ID  BIGINT       NOT NULL,
    JOB_NAME         VARCHAR(100) NOT NULL,
    CREATE_TIME      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    START_TIME       DATETIME              DEFAULT NULL,
    END_TIME         DATETIME              DEFAULT NULL,
    STATUS           VARCHAR(10),
    EXIT_CODE        VARCHAR(2500),
    EXIT_MESSAGE     VARCHAR(10000),
    LAST_UPDATED     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (JOB_EXECUTION_ID),
    UNIQUE IDX_JOB_INST(JOB_INSTANCE_ID)
) ENGINE=InnoDB;

CREATE TABLE BATCH_JOB_CONTEXT
(
    CONTEXT_ID      BIGINT       NOT NULL AUTO_INCREMENT,
    JOB_INSTANCE_ID BIGINT       NOT NULL,
    JOB_NAME        VARCHAR(100) NOT NULL,
    JOB_CONTEXT     LONGTEXT,
    CREATE_TIME     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (CONTEXT_ID),
    UNIQUE UNIQ_JOB_INST(JOB_INSTANCE_ID)
) ENGINE=InnoDB;

CREATE TABLE BATCH_STEP_EXECUTION
(
    STEP_EXECUTION_ID  BIGINT       NOT NULL AUTO_INCREMENT,
    VERSION            BIGINT       NOT NULL DEFAULT 0,
    JOB_NAME           VARCHAR(100) NOT NULL,
    JOB_INSTANCE_ID    BIGINT       NOT NULL,
    JOB_EXECUTION_ID   BIGINT       NOT NULL,
    STEP_NAME          VARCHAR(100) NOT NULL,
    CREATE_TIME        DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    START_TIME         DATETIME              DEFAULT NULL,
    END_TIME           DATETIME              DEFAULT NULL,
    STATUS             VARCHAR(10),
    COMMIT_COUNT       BIGINT,
    READ_COUNT         BIGINT,
    FILTER_COUNT       BIGINT,
    WRITE_COUNT        BIGINT,
    READ_SKIP_COUNT    BIGINT,
    WRITE_SKIP_COUNT   BIGINT,
    PROCESS_SKIP_COUNT BIGINT,
    ROLLBACK_COUNT     BIGINT,
    EXECUTION_CONTEXT  VARCHAR(2000),
    EXIT_CODE          VARCHAR(2500),
    EXIT_MESSAGE       VARCHAR(10000),
    LAST_UPDATED       DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (STEP_EXECUTION_ID),
    KEY                IDX_JOB_EXECUTION_ID(JOB_EXECUTION_ID)
) ENGINE=InnoDB;

CREATE TABLE BATCH_STEP_CONTEXT
(
    CONTEXT_ID      BIGINT       NOT NULL AUTO_INCREMENT,
    JOB_INSTANCE_ID BIGINT       NOT NULL,
    STEP_NAME       VARCHAR(100) NOT NULL,
    STEP_CONTEXT    LONGTEXT,
    CREATE_TIME     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (CONTEXT_ID),
    UNIQUE UNIQ_JOB_INST_STEP(JOB_INSTANCE_ID, STEP_NAME)
) ENGINE=InnoDB;
